/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniproyecto.GUI;

/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg_1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaJ = new javax.swing.JList<>();
        btnDel = new javax.swing.JButton();
        btnRes = new javax.swing.JButton();
        btnMatch = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnUpd = new javax.swing.JButton();
        IMG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));

        Bg_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaJ.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaJ);

        Bg_1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 360));

        btnDel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDel.setText("Eliminar");
        btnDel.setBorder(null);
        Bg_1.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 100, 30));

        btnRes.setBackground(new java.awt.Color(30, 30, 30));
        btnRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproyecto/IMG/IMG/Img/Re.png"))); // NOI18N
        btnRes.setBorder(null);
        btnRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResActionPerformed(evt);
            }
        });
        Bg_1.add(btnRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 50, 40));

        btnMatch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMatch.setText("Partido");
        btnMatch.setBorder(null);
        Bg_1.add(btnMatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 150, 60));

        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreate.setText("Crear");
        btnCreate.setBorder(null);
        Bg_1.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 150, 60));

        btnUpd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpd.setText("Actualizar");
        btnUpd.setBorder(null);
        Bg_1.add(btnUpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 150, 60));

        IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproyecto/IMG/IMG/Img/Imagen_inicio.jpg"))); // NOI18N
        Bg_1.add(IMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg_1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg_1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg_1;
    private javax.swing.JLabel IMG;
    private javax.swing.JList<String> ListaJ;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnMatch;
    public javax.swing.JButton btnRes;
    private javax.swing.JButton btnUpd;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
